#!/bin/bash
if [ -p /dev/stdin ]; then
    if [[ $1 == '-s' ]]; then
        while IFS= read line; do
            comma="${line:0:1}.${line:1}"
            pow=$(echo $line | wc -c)
            pow=$((pow-2))
            echo "$comma*e$pow"
        done
    else
        while IFS= read line; do
            substings=$(echo "$line" | rev | fold -w 3)
            folded=$(echo $substings | rev)
            word=$(for sting in $folded; do printf "$sting'"; done)
            echo $word | sed 's/.$//'
        done
    fi
else
    if [[ $1 == '-s' ]]; then
        input=$2
        comma="${input:0:1}.${input:1}"
        pow=$(echo $input | wc -c)
        pow=$((pow-2))
        echo "$comma*e$pow"
    else
        substings=$(echo "$1" | rev | fold -w 3)
        folded=$(echo $substings | rev)
        word=$(for sting in $folded; do printf "$sting'"; done)
        echo $word | sed 's/.$//'
    fi
fi